### PR TITLE
update: First pass at Export flow and table

### PR DESCRIPTION
**Pull request by isTravis**
A first pass at layout and flow for the Exports tab. Currently it just has stubs for the area where alignment (client-side) and real export generation (server-side) will go. 

It adds the `Exports` table to the prisma schema. We'll likely have to update this once we decide how we want versions to interact with the `export` object. We can discuss that next time we sync.

2V0lRTvXgF

### CODE REVIEW

**Review by octref — APPROVED** [review]
Great first step for exports! For the prisma schema, what are you using for formatting them? When I run `npx prisma format` or use the format feature in https://marketplace.visualstudio.com/items?itemName=Prisma.prisma, I see 2 spaces indentation.

**Comment by isTravis** [comment]
Hmm strange on the formatting. I use the Prisma extension formatter that you link to. In my VS settings, I have the following, and just run the `Format` command. I have a Prettier setting that says `tabWidth: 4` - but I would assume that wouldn't impact the Prisma formatting

```
"[prisma]": {
	"editor.defaultFormatter": "Prisma.prisma"
},
```

**Comment by isTravis** [comment]
Yup - running `npx prisma format` brings it to 2 spaces. I suppose I could adjust my default `tabsize` to 2 - but I gotta get my eyes to adjust to that ha! We could also stick `npx prisma format` on the git commit hook.

**Comment by octref** [comment]
I added a rule to automatically do that as you git-commit: 7e4904bb7f6c23a9b092c0787eb6e9c4165f15a6

Meanwhile you can do this in settings.json so it only applies to prisma.schema:

```json
{
  "[prisma]": {
    "editor.tabSize": 2
  }
}
```

**Comment by isTravis** [comment]
Oh duh - right. That's perfect - thanks!

**Pull request merged**
